baseurl = "https://ozlocke.github.io/the-queer-sticker-depot/"
title = "The Queer Sticker Depot"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-gb"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = "A collection of free to use sticker designs for furthering the \"gay agenda\"!"
  copyright = "&copy;2023 Oz Locke"
  sidebarAbout = [
    "Here you will find a collection of sticker designs that you are free* to use to spread support and awareness for queer folks around the world.",
    "Click an image to go to the folder for that image on git. From there you can click on the link to the file type you want** and then click download to the right just above the image.",
    "<i>You may also submit your own designs for consideration via the \"Submit designs\" button bellow",
    "* See Terms<br>** Most sticker printers will appreciate you providing them with the PDF</i>"
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "you@yoursite.com"

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Terms"
  url = "terms/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  facebook      = "https://www.facebook.com/transinformative"
  email         = "oz.locke@gmail.com"
  github        = "https://github.com/OzLocke/the-queer-sticker-depot"
